#!/usr/bin/env bash

red(){
	if [ $1 -eq 0 ]; then
		echo -n $1
	else
		echo -en "\033[0;31m$1\033[0m"
	fi
}

green(){
	if [ $1 -eq 0 ]; then
		echo -n $1
	else
		echo -en "\033[0;32m$1\033[0m"
	fi
}

git_status_all(){
	git for-each-ref --format="%(refname:short) %(upstream:short)" refs/heads | \
	while read local remote
	do
	    # [ -z "$remote" ] && continue
	    git rev-list --left-right ${local}...${remote} -- 2>/dev/null >/tmp/git_upstream_status_delta || continue
	    [ -z "$remote" ] && remote="\033[0;31mNO REMOTE\033[0m"
	    LEFT_AHEAD=$(grep -c '^<' /tmp/git_upstream_status_delta)
	    RIGHT_AHEAD=$(grep -c '^>' /tmp/git_upstream_status_delta)
	    echo -e "$local (ahead $(green $LEFT_AHEAD)) | (behind $(red $RIGHT_AHEAD)) $remote"
	done
}

while :; do
    case $1 in
        -a|--all) flag_all=true;
        ;;
        -r|--remote) flag_remote=true;
        ;;
        -ar|-ra) flag_remote=true; flag_all=true;
        ;;
        *) break
    esac
    shift
done


if [ "$flag_all" = true ] ; then
	git branch -a
	if [ "$flag_remote" = true ] ; then
		echo -n "Origin URL: "
		git config --get remote.origin.url
		git fetch --dry-run --all -qq
	fi
    git_status_all
    git status -s --ahead-behind
else
	git status -svb
fi

