#!/bin/bash

string_length=20

if [ 0 -ne $# ]
then
    # assign the first command line param, no check, if it is a number, though!
    string_length=$1
fi

</dev/urandom tr -dc 'A-Za-z0-9!"#$%&'\''()*+,-./:;<=>?@[\]^_`{|}~' | head -c $string_length ; echo