#!/usr/bin/env bash

STRING_LENGTH=20
MINIMAL_SYMBOL_CHARACTERS='A-Za-z0-9!#$(),-./:?@|'
CHARACTERS='A-Za-z0-9!"#$%&'\''()*+,-./:;<=>?@[\]^_`{|}~'

unknow_arg(){
	printf 'ERROR: Unknown option: %s\n' "$1" >&2
	exit
}

while :; do
    case $1 in
        -h|-\?|--help)
            usage
            exit
            ;;

        --*[a-z]) #
            long_option="${1#*--}"
            if [[ $long_option == "alpha" ]]; then
                ALPHANUMERIC=true
            elif [[ $long_option == "minimal" ]]; then
                MINIMAL=true
            elif [[ $long_option == "clipboard" ]]; then
                CLIPBOARD=true
            elif [[ $long_option == "verbose" ]]; then
                VERBOSE=true
            else
            	unknow_arg $1
            fi            
            ;;

        -*[a-z])
            options="${1#*-}"
            for (( i=0; i<${#options}; i++ )); do
              	char="${options:$i:1}"
	            if [[ $char == "c" ]]; then
	                CLIPBOARD=true
	            elif [[ $char == "m" ]]; then
	                MINIMAL=true
	            elif [[ $char == "a" ]]; then
	                ALPHANUMERIC=true
	            elif [[ $char == "v" ]]; then
	                VERBOSE=true
	            else
	            	unknow_arg -$char
	            fi
            done
            ;;

        -?*)
        	unknow_arg $1
            ;;

        *)
	        if [ "$1" ]; then
	            STRING_LENGTH=$1
	        else
	            break
	        fi
	        ;;
    esac
    shift
done

re='^[0-9]+$'
if ! [[ $STRING_LENGTH =~ $re ]] ; then
   echo "error: Not a number" >&2; exit 1
fi

if [ "$ALPHANUMERIC" = true ]; then
	CHARACTERS='A-Za-z0-9'
elif [ "$MINIMAL" = true ]; then
	CHARACTERS=$MINIMAL_SYMBOL_CHARACTERS
fi

random_string=$(</dev/urandom tr -dc $CHARACTERS | head -c $STRING_LENGTH)

if [ "$CLIPBOARD" = true ]; then
	echo -n $random_string | xclip -selection c
else
	echo $random_string
fi
