#!/usr/bin/env python3

import subprocess
import sys

if len(sys.argv) != 4:
    raise ValueError("Please specify <input file name> <speed> <output file name>")

speed = 1. * float(sys.argv[2])
file_input = sys.argv[1]
file_output = sys.argv[3]

cmd = 'ffmpeg -i %s -filter_complex [0:v]setpts=%s*PTS[v];[0:a]atempo=%s[a] -map [v] -map [a] %s'%(file_input, 1/speed, speed, file_output)

print(cmd.split())
# raise

# ffmpeg -i input.mkv -filter_complex [0:v]setpts=0.625*PTS[v];[0:a]atempo=1.61[a]" -r 48 -map "[v]" -map "[a]" output.mkv
# ffmpeg -i input.mkv -filter_complex "[0:v]setpts=0.871*PTS[v];[0:a]atempo=1.15[a]" -map "[v]" -map "[a]" output.mkv



process = subprocess.Popen(cmd.split(), stdout=subprocess.PIPE)
output, error = process.communicate()